#!/bin/bash
#KellyShyno
#Vinge
#version: 1.0.0

chmod -R a+rx *;
number='^[0-9]+$';

installing()
{
echo
}


banner()
{
clear;
sleep 0.1;
echo -e '\e[1;37m    ______\e[0m';
echo -e '\e[1;37m  _|      |_  \e[1;37mVinge\e[0m';
echo -e '\e[1;37m (__________) \e[1;30mv.1.0.0\e[0m';
echo "";
}


error()
{
clear; echo -e "\e[1;31mERROR: write the correct sign..\e[0m"; sleep 0.6;
}


input()
{
echo "";
echo -en "\e[1;30m (\e[0m""\e[1;37mx\e[0m""\e[1;30m_\e[0m""\e[1;37mx\e[0m";
echo -en "\e[1;30m)\e[0m" "\e[1;37m> \e[0m";
}


backOrExit()
{
echo -e "\e[1;30mTo back: 'b' | To exit: 'x'\e[0m";
echo "";
}


anyKey()
{
echo "";
echo -en "\e[1;30mpress any key: \e[0m";
 read choice
    case $choice in
"") $1; ;;
*) $1; ;;
    esac;
}


decryptFile()
{
banner;
backOrExit;
echo -e "\e[1;30mdecrypt file\e[0m";
echo "";
echo -en "\e[37mEnter the path to file: \e[0m";
 read filePath
echo "";
  if [[ $filePath == "x" ]]; then
echo ""; exit 0;
  elif [[ $filePath == "b" ]]; then
encryptOrDecryptFile;
  elif [[ $filePath =~ $number ]]; then
error; decryptFile;
  elif [[ $filePath == "" ]]; then
error; decryptFile;
  else
ccdecrypt "$filePath";
  case $? in
0) #checking the last signs
    if [[ ${filePath: -4} == '.cpt' ]]; then
filePath=$( echo $filePath| rev | cut -c 5- | rev );
    fi;
mv "$filePath" data/files/decryptedFiles/;
banner;
echo -en "\e[1;37m$filePath \e[0m";
echo -e "\e[1;30mis successfully decrypted";
echo -en "\e[1;30mThe file is located in \e[0m"
echo -e "\e[1;37mVinge/data/files/decryptedFiles\e[0m"; ;;
  esac;
anyKey encryptOrDecryptFile;
  fi;
}


encryptFile()
{
banner;
backOrExit;
echo -e "\e[1;30mencrypt file\e[0m";
echo "";
echo -en "\e[37mEnter the path to file: \e[0m";
 read filePath
echo "";
  if [[ $filePath == "x" ]]; then
echo ""; exit 0;
  elif [[ $filePath == "b" ]]; then
encryptOrDecryptFile;
  elif [[ $filePath =~ $number ]]; then
error; encryptFile;
  elif [[ $filePath == "" ]]; then
error; encryptFile;
  else
ccencrypt "$filePath";
    case $? in
0) banner;
mv "$filePath.cpt" data/files/encryptedFiles/;
echo -en "\e[1;37m$filePath \e[0m";
echo -e "\e[1;30mis successfully encrypted";
echo -en "\e[1;30mThe file is located in \e[0m"
echo -e "\e[1;37mVinge/data/files/encryptedFiles\e[0m"; ;;
    esac;
anyKey encryptOrDecryptFile;
  fi;
}


encryptOrDecryptFile()
{
banner;
backOrExit;
echo -e "\e[37m1.encrypt\e[0m";
echo -e "\e[37m2.decrypt\e[0m";
input;
 read choice
    case $choice in
1) encryptFile; ;;
2) decryptFile; ;;
"b") pentest; ;;
"x") echo ""; exit 0; ;;
*) error; encryptOrDecryptFile; ;;
    esac;
}


searchByNick()
{
echo
}


metadata()
{
banner;
backOrExit;
echo -e "\e[1;30mmetadata\e[0m";
echo "";
echo -en "\e[37mEnter the path to file: \e[0m";
 read filePath
echo "";
  if [[ $filePath == "x" ]]; then
echo ""; exit 0;
  elif [[ $filePath == "b" ]]; then
pentest;
  elif [[ $filePath =~ $number ]]; then
error; metadata;
  elif [[ $filePath == "" ]]; then
error; metadata;
  else
echo "" >> data/log/metadata/metadata.md;
echo "" >> data/log/metadata/metadata.md;
exiftool "$filePath" | tee -a data/log/metadata/metadata.md;
anyKey pentest;
  fi;
}


siteInfo()
{
banner;
backOrExit;
}


pentest()
{
banner;
backOrExit;
#nickInfo
echo -en "\e[1;30m/ \e[0m""\e[37m1\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37msite info\e[0m";
echo -en "\e[1;30m/ \e[0m""\e[37m2\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37mmetadata\e[0m";
echo -en "\e[1;30m/ \e[0m""\e[37m3\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37msearch by nick\e[0m";
echo -en "\e[1;30m/ \e[0m""\e[37m4\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37mencrypt file\e[0m";
input;
 read choice
  case $choice in
1) siteInfo; ;;
2) metadata; ;;
3) searchByNick; ;;
4) encryptOrDecryptFile; ;;
"b") shyno; ;;
"x") echo ""; exit 0; ;;
*) error; pentest; ;;
  esac;
}


clearLogExtraBlock()
{
banner;
echo -e "\e[1;30m$logChoice cleared\e[0m"; sleep 1; clearLog;
}


clearLog()
{
banner;
backOrExit;
echo -e "\e[1;30mclear log\e[0m";
echo "";
echo -e "\e[37m1.site info\e[0m";
echo -e "\e[37m2.metadata\e[0m";
echo -e "\e[37m3.search by nick\e[0m";
echo -e "\e[37m4.phone number info\e[0m";
input
 read choice
  case $choice in
1) logChoice="site info log";
echo '#site info log' > data/log/siteInfo/siteInfo.md; ;;
2) logChoice="metadata log";
echo '#metadata log' > data/log/metadata/metadata.md; ;;
3) logChoice="search by nick log";
echo '#search by nick log' >data/log/searchByNick/searchByNick.md; ;;
4) logChoice="phone number info log";
echo '#phone number info log' >data/log/phoneNumberInfo/phoneNumberInfo.md; ;;
"b") log; ;;
"x") echo ""; exit 0; ;;
*) error; clearLog; ;;
  esac;
clearLogExtraBlock; clearLog;
}


openLog()
{
banner;
backOrExit;
echo -e "\e[1;30mopen log\e[0m";
echo "";
echo -e "\e[37m1.site info\e[0m";
echo -e "\e[37m2.metadata\e[0m";
echo -e "\e[37m3.search by nick\e[0m";
echo -e "\e[37m4.phone number info\e[0m";
input
 read choice
  case $choice in
1) clear; less data/log/siteInfo/siteInfo.md; openLog; ;;
2) clear; less data/log/metadata/metadata.md; openLog; ;;
3) clear; less data/log/searchByNick/searchByNick.md; openLog; ;;
4) clear; less data/log/phoneNumberInfo/phoneNumberInfo.md; openLog; ;;
"b") log; ;;
"x") echo ""; exit 0; ;;
*) error; openLog; ;;
  esac;
}


log()
{
banner;
backOrExit;
echo -e "\e[37m1.open log\e[0m";
echo -e "\e[37m2.clear log\e[0m";
input
 read choice
  case $choice in
1) openLog; ;;
2) clearLog; ;;
"b") shyno; ;;
"x") echo ""; exit 0; ;;
*) error; log; ;;
  esac;
}


aboutProgram()
{
echo
}


shyno()
{
banner;
echo -e "\e[1;30mTo exit: 'x'\e[0m";
echo "";
echo -en "\e[1;30m/ \e[0m""\e[37m1\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37mpentest\e[0m";
echo -en "\e[1;30m/ \e[0m""\e[37m2\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37mlog\e[0m";
echo -en "\e[1;30m/ \e[0m""\e[37m3\e[0m"
echo -e "\e[1;30m / \e[0m""\e[37mabout program\e[0m";
input;
 read choice
  case $choice in
1) pentest; ;;
2) log; ;;
3) aboutProgram; ;;
"x") echo ""; exit 0; ;;
*) error; shyno; ;;
  esac;
}
shyno;
